### ISSUE TITLE
installing on ubuntu 20

### ISSUE THREAD

**Issue by craigham** [VeselaHouba/ansible-role-bareos#1]
Hi,

I was attempting to use this role to install Bareos on ubuntu 20.04.

I was getting tripped up with the monitoring packages install.

- name: Install packages for monitoring
  apt:
    name:
      - python-psycopg2
      - python-mysqldb
      - python3-psycopg2
      - python3-mysqldb

Apparently the python 2 versions are not avail on Ubuntu 20.  I changed it and added a variable 'bareos_apt_monitoring_packages' which defaults to the list of 4 packages above, but lets me override and remove the python 2 versions.

eg.
- name: Install packages for monitoring
  apt:
    name: "{{ bareos_apt_monitoring_packages }}"

Does this seem like a reasonable approach?  I'm not too experienced with ansible, and just getting started with bareos.

I also added an Ubuntu20.yml file to my vars folder, which was pretty straightforward.

thanks,
Craig

**Comment by VeselaHouba** [comment]
Thanks for hints. Feel free to create PR next time :)
Version 1.0.8 should appear in galaxy once the drone pipeline finishes
https://drone.m-cloud.cz/VeselaHouba/ansible-role-bareos/65
