### ISSUE TITLE
add webui-admin console

### ISSUE THREAD

**Issue by craigham** [VeselaHouba/ansible-role-bareos#3]
What do you think about this as a feature?  It would add the webui admin console file if the variable (ie. bareos_webui_admin_console) is set

something like:

bareos_webui_admin_console:
  name: admin
  password: secret
  tlsenable: false

Then the corresponding admin.conf would be created in the console folder.  Could use template ansible task to do this iff the variable is present.

I would be happy to implement and submit a PR if you think this would be useful, and open to suggestions if you would like to tweak implementation suggested above.

cheers,
Craig

**Comment by VeselaHouba** [comment]
Sure, go ahead and open PR.

**Comment by VeselaHouba** [comment]
resolved by #4
